version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${PGDBPASS?no postgres password set with env variable PGDBPASS}
    volumes:
      - ./resources/data:/var/lib/postgresql/data
      - ./resources/config/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080